# Project

Implementation of VO

## Import Modules

In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
import math
import scipy.signal
import scipy.linalg
import mae6292.tools as mae6292
import importlib

from mae6292.imshow import cv2_imshow

# VO - KITTI

The following codes perform VO for KITTI dataset, for the first 10 frames.

## Boostrapping

Bootstrapping to initilize VO has been implemented by
```
keypoints0, p_W0, R1, T1 = mae6292.VO_bootstrap(img0, img1, K, display = False)   
```

In [3]:
#open a new window for plot
%matplotlib tk 

# load K and first two images
K = np.loadtxt('KITTI/K.txt')
img0 = cv2.imread('KITTI/000000.png', cv2.IMREAD_GRAYSCALE)
img1 = cv2.imread('KITTI/000002.png', cv2.IMREAD_GRAYSCALE)

# PARAMETERS
param_bootstrap = {
    # keypoints
    'W_harris_patch' : 4, # size of harris patch
    'kappa_harris' : 0.08, # kappa for harris score
    'N_keypoint' : 2000, # number of keypoints to be detected
    'W_nms' : 8, # patch size for non-maximum supression
    # KLT
    'W_KLT' : 4, # patch size for KLT
    'tol_KLT_bidir' : 1, # tolerence of bidirectional error
    # find essential matrix
    'tol_E' : 1, # tolerence for epipolar line distance
    'tol_E_RANSAC_prob' : 0.99, # eseential matrix RANSAC probability
    # triangulation
    'tol_TRI_mu' : 1e-3, # tolerence for the singular value ratio
    'tol_TRI_rep' : 1 # tolerence for the reprojection error
}

keypoints0, p_W0, R1, T1 = mae6292.VO_bootstrap(img0, img1, K, param_bootstrap, display = True)   

print('N_keypoints0=',len(keypoints0))


N_keypoints0= 733


## Localization and Mapping


For the first 10 frames, the sequential process for localization and mapping has been implemented by
```
    R, T, S, C, fig = mae6292.VO_localization_mapping(i_frame, K, img, img_pre, S_pre, C_pre, display_process=True)
```
Each frame is saved under the folder `KITTI_output`

In [4]:
#open a new window for plot
%matplotlib tk 
importlib.reload(mae6292)

param = {
    # keypoints
    'W_harris_patch' : 4, # size of harris patch
    'kappa_harris' : 0.08, # kappa for harris score
    'N_keypoint' : 2000, # number of keypoints to be detected
    'W_nms' : 8, # patch size for non-maximum supression
    # KLT
    'W_KLT' : 4, # patch size for KLT
    'tol_KLT_bidir' : 1, # tolerence of bidirectional error
    # triangulation
    'tol_TRI_mu' : 1e-3, # tolerence for the singular value ratio
    'tol_TRI_rep' : 0.5, # tolerence for the reprojection error
    # mapping
    'tol_keypoints_new' : 18 # new keypoints should be district from the tracked keypoints by this distance
} # up to 1000 

# iniitlize iteration using img0
img_pre = img0
S_pre = mae6292.state(keypoints0, p_W0, [np.zeros((3,1))])
C_pre = mae6292.candidate([],[],[],[])

# number of frames to process
N_frames = 10
display_process = True

# variables to save the vehicle location and the keypoints in the W-frame 
T_W = np.zeros((3,N_frames+1))
p_W = p_W0

for i_frame in range(1,N_frames+1):
    
    print('i_frame=',i_frame)

    # VO localization and mapping
    img = cv2.imread("KITTI/{:06d}.png".format(i_frame),cv2.IMREAD_GRAYSCALE)
    img_rgb = cv2.cvtColor(cv2.imread("KITTI/{:06d}.png".format(i_frame)), cv2.COLOR_BGR2RGB)
    R, T, S, C, fig = mae6292.VO_localization_mapping(i_frame, img, img_rgb, img_pre, S_pre, C_pre, K, param, display_process)
    img_pre, S_pre, C_pre = img, S, C

    # save figure 
    if display_process:
        fig.savefig("KITTI_output/{:06d}.png".format(i_frame))
        # !!!NOTE!!!:
        # when N_frames is large, uncomment the following to avoid generating too many figures in your screeen
        # plt.close(fig)

    # save the vehicle location and the distinct keypoints 
    T_W[:,i_frame] = (-R.T@T).flatten()
    p_W_dist = scipy.spatial.distance.cdist( S.p_W.T, p_W.T , 'euclidean')
    index_distinct = np.where( np.min(p_W_dist, axis=1) > 3 )[0]
    p_W = np.append(p_W, S.p_W[:,index_distinct], axis=1)

    # print pose
    print('R=',R)
    print('T_W=',(-R.T@T).flatten())
    print(' ')




i_frame= 1
R= [[ 0.99998921  0.00276061  0.00373741]
 [-0.00276799  0.99999423  0.00196964]
 [-0.00373195 -0.00197996  0.99999108]]
T_W= [ 0.00833623 -0.00609119  0.4921098 ]
 
i_frame= 2
S_pre= 728 , KLT_matched= 721 , PnP_inliers= 720 , S_new =  832
C_pre= 740 , KLT_matched= 278 , TRI_inliers= 112 , C_new =  329
R= [[ 0.99996636  0.00126534  0.00810466]
 [-0.00129361  0.99999309  0.00348433]
 [-0.00810019 -0.00349469  0.99996109]]
T_W= [ 0.00736367 -0.01118748  1.00122646]
 
i_frame= 3
S_pre= 832 , KLT_matched= 744 , PnP_inliers= 741 , S_new =  771
C_pre= 329 , KLT_matched= 141 , TRI_inliers= 30 , C_new =  375
R= [[ 0.99992348  0.00117117  0.01231551]
 [-0.00122994  0.99998789  0.00476508]
 [-0.01230978 -0.00477987  0.99991281]]
T_W= [ 0.00285198 -0.01798042  1.52125257]
 
i_frame= 4
S_pre= 771 , KLT_matched= 694 , PnP_inliers= 687 , S_new =  723
C_pre= 375 , KLT_matched= 145 , TRI_inliers= 36 , C_new =  340
R= [[ 9.99844491e-01 -2.61724494e-04  1.76330562e-02]
 [ 1.71097809e-04  9.9

## Generate Trajectory Map

The following codes visualize the vehicle trajectory and the keypoints in the W-frame. 

(You may need to adjust th eaxis limit)

In [5]:
fig = plt.figure()
ax = plt.axes(projection = '3d')
ax.plot(T_W[0,:], T_W[1,:], T_W[2,:], 'b')
ax.scatter(p_W[0,:], p_W[1,:], p_W[2,:], s=1, c='r', marker='o')
ax.set_xlim(-10,20)
ax.set_zlim(-2,20)
ax.set_xlabel('x',fontsize=6)
ax.set_ylabel('y',fontsize=6)
ax.set_zlabel('z',fontsize=6)
ax.view_init(elev=0., azim=-90)

## Generate Video

The output images can be converted into a video as follows.

In [7]:
img_array = []

for i_frame in range(1,N_frames):
    filename = "KITTI_output/{:06d}.png".format(i_frame)
    img = cv2.imread(filename)
    img_array.append(img)

height, width, layers = img.shape
size = (width,height)

fps = 3
codec = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('KITTI_output/KITTI.mp4',codec, fps, size)
 
for i in range(len(img_array)):
    out.write(img_array[i])

out.release()

## Problems 1 and 2

Follow the directions in `project_prob1.ipynb`and `project_prob2.ipynb`